name: Spotfiy in Github

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: debian-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup golang
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.4' 

      - name: build app
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build cmd/app/main.go

      - name: copy build to vps
        uses: appleboy/scp-action@master
        with:
          host: ${{secret.VPS_HOST}}
          username: ${{secret.VPS_USER}}
          key: ${{secret.VPS_SSH_KEY}}
          source: "app,config.yml" 
          target: "/home/lacon/deploy/app"

      - name: restart systemd
        uses: appleboy/scp-action@master
        with:
          host: ${{secret.VPS_HOST}}
          username: ${{secret.VPS_USER}}
          key: ${{secret.VPS_SSH_KEY}}
          script: |
            cd /home/lacon/deploy/app
            sudo systemctl restary myapp
